name: Podman test
on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
      - name: Create container
        run: |
          podman version
          apt-cache policy podman

          echo $DBUS_SESSION_BUS_ADDRESS
          sudo bash -c 'echo $DBUS_SESSION_BUS_ADDRESS'

          cat <<EOF | sudo podman --log-level debug build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF
