name: Podman test
on:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-20.04
    steps:
      - name: Create container
        run: |
          podman version

          cat <<EOF | sudo su -c 'podman build -t test-container -f - .'
          FROM fedora:36
          RUN echo test
          EOF
