name: Podman test
on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
      - name: Create container
        run: |
          podman version
          apt-cache policy podman

          echo regular user
          export

          echo sudo
          sudo bash -c export

          echo sudo -i
          sudo -i bash -c export

          cat <<EOF | sudo -i podman build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF

          cat <<EOF | sudo podman build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF
