name: Podman test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Create container
        run: |
          cat <<EOF | sudo XDG_RUNTIME_DIR= podman build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF
