name: Podman test
on:
  workflow_dispatch:

jobs:
  b:
    runs-on: ubuntu-20.04
    steps:
      - name: Create container
        run: |
          cat <<EOF | sudo -E XDG_RUNTIME_DIR=/run/user/0 podman build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF
